# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 07:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]*$')], verbose_name='First Name')),
                ('user_last_name', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]*$')], verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('user_dob', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('user_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('user_github', models.CharField(blank=True, max_length=100, verbose_name='Github Profile')),
                ('user_linkedin', models.CharField(blank=True, max_length=100, verbose_name='Linkedin Profile')),
                ('user_bio', models.CharField(blank=True, max_length=1000, verbose_name='Short Bio')),
                ('user_occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('user_nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True, verbose_name='Course Name')),
                ('course_bio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course Description')),
                ('course_language', models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi')], max_length=25, verbose_name='Course Language')),
                ('course_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], max_length=20, verbose_name='Course Difficulty')),
                ('course_fees', models.IntegerField(blank=True, help_text='5 digits maximum', null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)], verbose_name='Course Fees')),
                ('course_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('course_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('checkout_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_time', models.DateTimeField(auto_now_add=True)),
                ('course_enrolled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModules',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100, unique=True, verbose_name='Module Name')),
                ('module_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Module Description')),
                ('module_duration', models.IntegerField(blank=True, help_text='3 digits maximum', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Duration of module')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.CourseEnrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.CourseModules')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('bank_ref_no', models.CharField(blank=True, max_length=20, null=True)),
                ('status_code', models.CharField(blank=True, max_length=500, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=500, null=True)),
                ('status_message', models.CharField(blank=True, max_length=170, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=20, null=True)),
                ('time_of_order', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Order'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set([('user', 'course')]),
        ),
    ]
